site_name: Skynet Wiki
site_description: Community driven doccumentation of sia.
site_author: Skynet Guide Contributors

use_directory_urls: false

theme:
    name: material
    favicon: static/assets/favicon.png
    logo: static/assets/favicon.png
    palette:
      primary: green
      scheme: slate

plugins:
  - i18n:
      default_language: en
      languages:
        en: english
        fr: français
        de: deutsch
        ru: русский
