site_name: Skynet Wiki
site_description: Community driven doccumentation of sia.
site_author: Skynet Guide Contributors

use_directory_urls: false

theme:
  name: material
  favicon: static/assets/favicon.png
  logo: static/assets/favicon.png
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

plugins:
  - search
  - i18n:
      default_language: en
      languages:
        en: English
        fr: Français
        de: Deutsch
        ru: Русский
