name: Build mkdocs and upload to skynet on PR
on: pull_request

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
          architecture: 'x64'
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip       # install pip
          python3 -m pip install -r requirements.txt # install requirements
      - name: Build site
        run: mkdocs build
      - name: Deploy to Skynet
        uses: kwypchlo/deploy-to-skynet-action@main
        with:
          upload-dir: site
          github-token: ${{ secrets.GITHUB_TOKEN }}
