name: Deploy Sky Guide to Skynet

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
  runs-on: ubuntu-latest

steps:
  — uses: actions/checkout@v2

  — uses: mhausenblas/mkdocs-deploy-gh-pages@master
  - run: mkdocs build

  — uses: kwypchlo/deploy-to-skynet-action@main
    with:
      upload-dir: site
      github-token: ${{ secrets.GITHUB_TOKEN }}
